---
departments:
  0U4: "華語中心"
  0U7: "教育學程"
  0U8: "交大遠距教學"
  0UB: "資訊技術服務中心"
  0UC: "圖書館"
  0UF: "衛保組(健康與護理)"
  0UH: "教務處"
  0UJ: "寫作中心"
  0UM: "計概小組"
  0UP: "台中一中科學班"
  '201': ILS(加速器光源科技與應用碩士學位學程)
  '202': SMT(聲音與音樂創意科技碩士學位學程)
  '203': ECS(電機資訊國際碩、博士學位學程)
  '204': IPS(光電系統研究所)
  '205': ILP(照明與能源光電研究所)
  '206': IIB(影像與生醫光電博士學位學程)
  '207': INS(網路與資訊系統博士學位學程)
  '211': IEE(電子研究所)
  '212': ICN(電控工程研究所)
  '213': ECM(電信工程研究所)
  '214': IME(機械工程學系)
  '215': IDI(顯示科技研究所)
  '216': ICV(土木工程學系)
  '217': ICP(資訊工程學系)
  '218': IMA(材料科學與工程學系)
  '219': IEV(環境工程研究所)
  '220': IMM(應用數學系數學建模與科學計算碩士班)
  '221': IEP(電子物理學系)
  '222': IAM(應用數學系)
  '223': GEE(電機工程學系)
  '224': IEO(光電工程學系)
  '225': IAC(應用化學系)
  '226': IST(統計學研究所)
  '227': IOP(物理研究所)
  '228': IBT(生物科技學系)
  '229': IBE(分子醫學與生物工程研究所)
  '230': IIE(生醫工程研究所)
  '231': IMS(管理科學系)
  '232': ITS(運輸與物流管理學系交通運輸碩博士班)
  '233': IEM(工業工程與管理學系)
  '234': IIM(資訊管理與財務金融系資訊管理碩博士班)
  '235': ITM(科技管理研究所)
  '236': ITT(運輸與物流管理學系物流管理碩博士班)
  '237': IBM(經營管理研究所)
  '238': ITL(科技法律研究所)
  '239': IOF(資訊管理與財務金融系財務金融碩博士班)
  '241': ICT(傳播研究所)
  '242': IAA(應用藝術研究所)
  '245': ILC(外國語文學系外國文學與語言學碩士班)
  '246': IMU(音樂研究所)
  '247': IAR(建築研究所)
  '248': IED(教育研究所)
  '249': ICS(社會與文化研究所)
  '251': IBI(生物資訊及系統生物研究所)
  '252': INT(材料科學與工程學系奈米科技碩博班)
  '253': INA(人文社會學系族群與文化碩士班)
  '255': IOC(資訊科學與工程研究所)
  '256': IOE(網路工程研究所)
  '257': ILE(多媒體工程研究所)
  '258': IMO(應用化學系分子科學碩博班)
  '259': ITE(英語教學研究所)
  '261': IBA(高階主管管理碩士學程)
  '262': IMS(管理學院碩士在職專班-管科組)
  '263': IEM(管理學院碩士在職專班-工管組)
  '264': IIM(管理學院碩士在職專班-資管組)
  '265': ITM(管理學院碩士在職專班-科管組)
  '266': ISR(工學院碩士在職專班-產安組)
  '267': IEC(電機學院碩士在職專班)
  '268': ITL(管理學院碩士在職專班-科法組)
  '269': IAP(工學院碩士在職專班-精密組)
  '270': IMI(工學院碩士在職專班-工程管理組)
  '271': ITT(管理學院碩士在職專班-物流組)
  '272': IOF(管理學院碩士在職專班-財金組)
  '273': INE(理學院碩士在職專班)
  '274': IBM(管理學院碩士在職專班-經管組)
  '275': ISE(工學院碩士在職專班-半導體組)
  '276': IET(工學院碩士在職專班-永續科技組)
  '278': IHC(客家社會與文化碩士在職專班)
  '279': IPC(資訊學院碩士在職專班)
  '280': IPT(光電科技碩士在職專班)
  '281': CST(國際半導體產業學院碩士班)
  '284': IBS(生醫科學與工程博士學位學程)
  '285': ISC(永續化學科技國際研究生博士學位學程)
  '286': IPP(光電博士學位學程)
  '287': IFD(平面顯示技術碩士學位學程)
  '288': GMBA(企業管理碩士學位學程)
  '289': IBN(跨領域神經科學博士學位學程)
  '290': IIT(資訊院資訊科技產業專班)
  '291': ISN(理院光電半導體奈米產專)
  '292': INC(通訊與網路科技產業專班)
  '293': IEL(電機產業專班)
  '294': IMN(微電子奈米科技產業專班)
  '295': IIC(IC設計產業專班)
  '296': IOD(光電顯示科技產業專班)
  '297': IMP(工院半導體材料製程產專)
  '298': IPM(跨領域分子科學國際碩士學位學程)
  '299': IAS(亞際文化研究國際碩士學位學程)
  2A1: "(人文社會學院院本部)"
  2B1: "(生物科技學院)"
  2C1: CCS(資訊學院)
  2E1: ICO(工學院)
  2I1: ICE(電機學院(研究所))
  2K1: IKS(客家文化學院)
  2M1: IOM(管理學院院本部)
  2M2: IOM(管理學院專班(共同課程))
  2O1: IPO(光電學院)
  2OA: IID(工院影像顯示科技產專)
  2OB: ICC(理學院IC製程化學產專)
  2S1: IOS(理學院院本部)
  2Y1: "(電機學院與資訊學院)"
  '308': DPN(奈米科學及工程學士學位學程)
  '309': DPS(理學院科學學士學位學程)
  '310': ECE(電機資訊學士班)
  '311': DEE(電子工程學系)
  '312': DCN(電機與控制工程學系)
  '313': ECM(電信工程學系)
  '314': DME(機械工程學系)
  '316': DCV(土木工程學系)
  '317': DCP(資訊工程學系)
  '318': DMA(材料科學與工程學系)
  '321': DEP(電子物理學系)
  '322': DAM(應用數學系)
  '323': UEE(電機工程學系)
  '324': DEO(光電工程學系)
  '325': DAC(應用化學系)
  '328': DBT(生物科技學系)
  '331': DMS(管理科學系)
  '332': DTM(運輸與物流管理學系)
  '333': DEM(工業工程與管理學系)
  '343': DFL(外國語文學系)
  '344': DIF(資訊管理與財務金融系)
  '353': DHS(人文社會學系)
  '354': DCT(傳播與科技學系)
  3A1: "(人文社會學院院本部)"
  3B1: "(生物科技學院)"
  3C1: CCS(資訊學院)
  3E1: DCO(工學院)
  3I1: DCE(電機學院(大學部))
  3K1: DKS(客家文化學院)
  3M1: DOM(管理學院院本部)
  3O1: DPO(光電學院)
  3S1: DOS(理學院院本部)
  3Y1: "(電機學院與資訊學院)"
  8AA: "機電整合學分學程"
  8AB: "製造自動化學分學程"
  8AC: "光電科技學分學程"
  8AD: "科技管理學分學程"
  8AE: "智慧財產權學分學程"
  8AF: "電腦軟體學分學程"
  8AG: "數位圖書資訊學分學程"
  8AH: "網路社會學分學程"
  8AI: "生物資訊學分學程"
  8AJ: "法律學分學程"
  8AK: "半導體製造管理學分學程"
  8AL: IMBA國際管理學分學程
  8AM: "生物電子學分學程"
  8AN: "電機資訊英語授課學分學程"
  8AO: "奈米科技學分學程"
  8AP: "文化研究學分學程"
  8AQ: "財務工程學分學程"
  8AR: 3C整合科技學分學程
  8AS: "網際網路學分學程"
  8AT: "積體電路設計第二專長學分學程"
  8AU: "人文與管理學分學程"
  8AV: "晶片系統商管學分學程"
  8AW: "台灣文化研究學分學程"
  8AX: "智慧化運輸學分學程"
  8AY: "人文與物流管理學分學程"
  8AZ: "數位娛樂與藝術學分學程"
  8BA: "管理與資訊學分學程"
  8BB: "資通安全學分學程"
  8BC: "社會與文化學分學程"
  8BD: "創意文化學分學程"
  8BE: "數位媒體學分學程"
  8BF: "傳播研究學分學程"
  8BG: "全球化與數位文化學分學程"
  8BH: "跨文化經典學分學程"
  8BI: "網路與社會學分學程"
  8BJ: "爭端解決與衝突管理學分學程"
  8BK: "系統與決策最優化學分學程"
  8BL: "數位典藏與數位創作π學分學程"
  8BM: "美國法學分學程"
  8BN: "音樂學分學程"
  8BO: "科技與社會學分學程"
  8BP: "心理學學分學程"
  8BQ: RFID及感測網路應用學分學程
  8BR: "高科技產業國際金融管理學分學程"
  8BS: "領袖人才培育學分學程"
  8BT: "生醫法律學分學程"
  8BU: "國際法律學分學程"
  8BV: "大學部雲端系統學分學程"
  8BW: "研究所雲端系統學分學程"
  8BX: "物聯網學分學程"
  8BY: "雲端計算學分學程"
  8BZ: "創業與創新學分學程"
  8CA: "數位動畫文創學分學程"
  8CB: "巨量資料分析學分學程"
  8CC: "高階繪圖與視訊技術學分學程"
  8CD: "創新科技藝術學分學程"
  8CE: "工學院國際學分學程"
  8CF: "生醫產業經營與法律學分學程"
  8FA: "電機學院:電機基礎學分學程"
  8FB: "資工系:程式設計學分學程"
  8FC: "資工系:資訊安全學分學程"
  8FD: "資工系:資訊系統學分學程"
  8FE: "資工系:資電學分學程"
  8FF: "資工系:多媒體學分學程"
  8FG: "資工系:網路學分學程"
  8FH: "管理學院:管理基礎學分學程"
  8FI: "外文系:華語教學學分學程"
  8FJ: "外文系:電影研究學分學程"
  8FK: "語言中心:英語榮譽學分學程"
  8FL: "客家學院:客家社會與文化學程"
  8FM: "人社系:人文社會學系核心學分學程"
  8FN: "人社系:社會學與人類學學分學程"
  8FO: "人社系:族群與文化學分學程"
  8FP: "傳科系:傳播科技學分學程"
  8FQ: "傳科系:媒體文化學分學程"
  8FR: "人社系:文化產業學分學程"
  8FS: "電子系:基礎電子學分學程"
  8FT: "電子系:電子學分學程"
  8FU: "電子系:生醫光電學分學程"
  8FV: "電子系:奈米電子學分學程"
  8FW: "電子系:通訊與多媒體學分學程"
  8FX: "電子系:晶片系統學分學程"
  8FY: "電機系:基礎學分學程"
  8FZ: "電機系:核心學分學程"
  8GA: "電機系:無線科技學分學程"
  8GB: "電機系:多媒體訊號處理學分學程"
  8GC: "電機系:系統控制學分學程"
  8GD: "電機系:系統晶片設計學分學程"
  8GE: "電機系:電力電子與能源科技學分學程"
  8GF: "電機系:機器人與仿生科技學分學程"
  8GG: "電機系:資訊通訊學分學程"
  8GH: "電機系:通訊科學與系統學分學程"
  8GI: "光電系:光波科學與光通訊學程"
  8GJ: "光電系:光電科技與光電子學程"
  8GK: "光電系:光學系統與資訊光學學程"
  8GL: "光電系:顯示科技學分學程"
